name: Golang linter

on:
  push:
    branches-ignores:
      - main
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'

permissions:
  contents: read

jobs:
  golang-ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.14

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: --skip-files _test.go
