name: Markdown linter

on:
  push:
    branches-ignores:
      - main
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-ci:
    name: Lint changelog file
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint markdown files
        uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .
          config_file: .markdownlint.json
          dot: true
