name: Code Analysis

on: [push,pull_request]

defaults:
  run:
    shell: bash

jobs:
  all:
    name: Code Quality
    runs-on: ubuntu-20.04
    steps:
      # Setup source code
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      # Test & Coverage
#      - name: Test & Coverage
#        run: go test -vet=off -coverprofile .report_coverage.out -json ./... > .report_test.json

      # Sonarqube
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v3
        with:
          version: "4.6.2.2472"

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarQube
        run: sonar-scanner
          -Dsonar.host.url="https://sonarcloud.io"
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
